name: gitflow

on: 
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'hotfix'
jobs:
  terraforminit:
    name: Terraform Init and Plan
    runs-on: sahil-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: C:\Users\Public\Ness_data\Cloud\test_new\GitHub_practice\GitHub_New_practice
